#!/bin/bash
# Quick status check after fix
echo "=== MT5 Quick Status $(date '+%Y-%m-%d %H:%M:%S UTC') ==="
echo ""
echo "MT5:     $(pgrep -f terminal64 > /dev/null && echo 'RUNNING' || echo 'DOWN')"
echo "Xvfb:    $(pgrep -x Xvfb > /dev/null && echo 'RUNNING' || echo 'DOWN')"
echo "VNC:     $(pgrep -x x11vnc > /dev/null && echo 'RUNNING' || echo 'DOWN')"
echo "Daemon:  $(pgrep -f mt5_status_daemon > /dev/null && echo 'RUNNING' || echo 'DOWN')"
echo ""
echo "Watchdog: $(crontab -l 2>/dev/null | grep -q mt5_watchdog && echo 'ACTIVE' || echo 'NOT SET')"
echo "Boot svc: $(systemctl is-enabled mt5-trading.service 2>/dev/null || echo 'NOT SET')"
echo ""
echo "Status JSON:"
cat /var/bots/mt5_status.json 2>/dev/null | python3 -m json.tool 2>/dev/null || echo "Not available"
echo ""
echo "Watchdog log (last 20 lines):"
tail -20 /var/log/mt5_watchdog.log 2>/dev/null || echo "No log yet"
