#!/bin/bash
# Trigger: v150
cd /root/MT5-PropFirm-Bot
echo "=== Post-Fix Status Check $(date -u '+%Y-%m-%d %H:%M UTC') ==="
echo ""
echo "=== Service Status ==="
echo "Service: $(systemctl is-active futures-bot)"
echo "PID: $(systemctl show futures-bot --property=MainPID --value)"
echo "Code: $(git log -1 --oneline)"
echo ""
echo "=== Last 50 lines of bot.log ==="
tail -50 logs/bot.log 2>/dev/null || echo "No log file found"
echo ""
echo "=== BLOCKED trades (should be zero after fix) ==="
grep -c "BLOCKED" logs/bot.log 2>/dev/null || echo "0"
echo ""
echo "=== Recent SIGNALS and TRADES ==="
grep -iE "SIGNAL|TRADE|BLOCKED|order|fill" logs/bot.log 2>/dev/null | tail -25 || echo "No signals"
echo ""
echo "=== Open Positions ==="
grep -iE "position.*open|active position|placed.*order" logs/bot.log 2>/dev/null | tail -10 || echo "No open positions"
echo "=== End ==="
