"""
PropFirmBot - Self-Learning Trade Analyzer
==========================================
Reads the EA's CSV journal and analysis files, performs deep analysis,
and generates recommendations for parameter adjustments.

This module runs periodically (cron job or manual) to:
1. Parse trade journal CSV files
2. Analyze patterns (time-based, symbol-based, strategy-based)
3. Detect losing patterns and suggest corrections
4. Generate parameter adjustment recommendations
5. Track performance over time (learning)
"""

import os
import sys
import json
import csv
from datetime import datetime, timedelta
from pathlib import Path
from collections import defaultdict
import numpy as np
import pandas as pd

# MT5 Common Files directory varies by OS
MT5_COMMON_DIR = os.environ.get(
    "MT5_COMMON_DIR",
    os.path.expanduser("~/.wine/drive_c/users/Public/Documents/MetaTrader 5/Terminal/Common/Files")
)

JOURNAL_DIR = Path(MT5_COMMON_DIR)
OUTPUT_DIR = Path(__file__).parent.parent / "backtest_results" / "analysis"


class TradeAnalyzer:
    """Deep trade analysis engine with self-learning capabilities."""

    def __init__(self, journal_dir=None, output_dir=None):
        self.journal_dir = Path(journal_dir) if journal_dir else JOURNAL_DIR
        self.output_dir = Path(output_dir) if output_dir else OUTPUT_DIR
        self.output_dir.mkdir(parents=True, exist_ok=True)

        self.trades = pd.DataFrame()
        self.analysis_history = []

    def load_journal(self, days_back=30):
        """Load trade journal CSV files from the last N days."""
        all_trades = []

        # Try loading from MT5 common files
        patterns = ["PropFirmBot_Journal_*.csv"]
        for pattern in patterns:
            for f in self.journal_dir.glob(pattern):
                try:
                    df = pd.read_csv(f)
                    all_trades.append(df)
                except Exception as e:
                    print(f"Warning: Could not read {f}: {e}")

        # Also check local backtest_results directory
        local_dir = Path(__file__).parent.parent / "logs"
        for f in local_dir.glob("PropFirmBot_Journal_*.csv"):
            try:
                df = pd.read_csv(f)
                all_trades.append(df)
            except Exception:
                pass

        if not all_trades:
            print("No journal files found. Checking for analysis CSV...")
            return self._load_analysis_csv()

        self.trades = pd.concat(all_trades, ignore_index=True)

        # Filter to closed trades only
        if "Type" in self.trades.columns:
            self.trades = self.trades[self.trades["Type"] == "CLOSE"].copy()

        # Parse datetime
        if "DateTime" in self.trades.columns:
            self.trades["DateTime"] = pd.to_datetime(self.trades["DateTime"], errors="coerce")
            cutoff = datetime.now() - timedelta(days=days_back)
            self.trades = self.trades[self.trades["DateTime"] >= cutoff]

        print(f"Loaded {len(self.trades)} closed trades")
        return len(self.trades) > 0

    def _load_analysis_csv(self):
        """Load the analysis CSV generated by the EA's TradeAnalyzer."""
        analysis_file = self.journal_dir / "PropFirmBot_Analysis.csv"
        if not analysis_file.exists():
            print(f"No analysis file found at {analysis_file}")
            return False

        try:
            self.analysis_data = pd.read_csv(analysis_file)
            print(f"Loaded EA analysis data: {len(self.analysis_data)} rows")
            return True
        except Exception as e:
            print(f"Error loading analysis CSV: {e}")
            return False

    def analyze_by_symbol(self):
        """Analyze performance per trading symbol."""
        if self.trades.empty or "Symbol" not in self.trades.columns:
            return {}

        results = {}
        for symbol in self.trades["Symbol"].unique():
            if pd.isna(symbol) or symbol == "":
                continue

            sym_trades = self.trades[self.trades["Symbol"] == symbol]
            pnl_col = "PnL" if "PnL" in sym_trades.columns else None
            if pnl_col is None:
                continue

            sym_trades_valid = sym_trades[pd.to_numeric(sym_trades[pnl_col], errors="coerce").notna()]
            pnl_values = pd.to_numeric(sym_trades_valid[pnl_col])

            wins = (pnl_values > 0).sum()
            losses = (pnl_values <= 0).sum()
            total = len(pnl_values)

            results[symbol] = {
                "trades": total,
                "wins": int(wins),
                "losses": int(losses),
                "win_rate": round(wins / total * 100, 1) if total > 0 else 0,
                "total_pnl": round(float(pnl_values.sum()), 2),
                "avg_pnl": round(float(pnl_values.mean()), 2) if total > 0 else 0,
                "max_win": round(float(pnl_values.max()), 2) if total > 0 else 0,
                "max_loss": round(float(pnl_values.min()), 2) if total > 0 else 0,
                "profit_factor": round(
                    float(pnl_values[pnl_values > 0].sum()) /
                    abs(float(pnl_values[pnl_values <= 0].sum()))
                    if pnl_values[pnl_values <= 0].sum() != 0 else 0, 2
                ),
                "recommendation": ""
            }

            # Generate recommendation
            r = results[symbol]
            if r["trades"] >= 5:
                if r["win_rate"] < 30:
                    r["recommendation"] = "REMOVE - Very poor win rate"
                elif r["win_rate"] < 40 and r["profit_factor"] < 1.0:
                    r["recommendation"] = "REDUCE RISK - Below average"
                elif r["win_rate"] > 55 and r["profit_factor"] > 1.5:
                    r["recommendation"] = "KEEP - Strong performer"
                else:
                    r["recommendation"] = "MONITOR - Average performance"

        return results

    def analyze_by_session(self):
        """Analyze performance by trading session (London/NY)."""
        if self.trades.empty or "DateTime" not in self.trades.columns:
            return {}

        results = {"London": {}, "NewYork": {}, "Other": {}}

        for _, trade in self.trades.iterrows():
            try:
                dt = trade["DateTime"]
                if pd.isna(dt):
                    continue
                hour = dt.hour

                if 7 <= hour < 12:
                    session = "London"
                elif 12 <= hour < 17:
                    session = "NewYork"
                else:
                    session = "Other"

                if "trades" not in results[session]:
                    results[session] = {"trades": 0, "wins": 0, "total_pnl": 0}

                pnl = float(trade.get("PnL", 0) or 0)
                results[session]["trades"] += 1
                results[session]["total_pnl"] += pnl
                if pnl > 0:
                    results[session]["wins"] += 1
            except (ValueError, TypeError):
                continue

        for session in results:
            r = results[session]
            if isinstance(r, dict) and "trades" in r and r["trades"] > 0:
                r["win_rate"] = round(r["wins"] / r["trades"] * 100, 1)
                r["avg_pnl"] = round(r["total_pnl"] / r["trades"], 2)
                r["total_pnl"] = round(r["total_pnl"], 2)

        return results

    def analyze_by_day_of_week(self):
        """Analyze performance by day of the week."""
        if self.trades.empty or "DateTime" not in self.trades.columns:
            return {}

        day_names = ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday"]
        results = {d: {"trades": 0, "wins": 0, "total_pnl": 0} for d in day_names}

        for _, trade in self.trades.iterrows():
            try:
                dt = trade["DateTime"]
                if pd.isna(dt):
                    continue
                day = day_names[dt.weekday()] if dt.weekday() < 5 else None
                if day is None:
                    continue

                pnl = float(trade.get("PnL", 0) or 0)
                results[day]["trades"] += 1
                results[day]["total_pnl"] += pnl
                if pnl > 0:
                    results[day]["wins"] += 1
            except (ValueError, TypeError, IndexError):
                continue

        for day in results:
            r = results[day]
            if r["trades"] > 0:
                r["win_rate"] = round(r["wins"] / r["trades"] * 100, 1)
                r["total_pnl"] = round(r["total_pnl"], 2)

        return results

    def analyze_streaks(self):
        """Analyze winning and losing streaks."""
        if self.trades.empty or "PnL" not in self.trades.columns:
            return {}

        pnl_values = pd.to_numeric(self.trades["PnL"], errors="coerce").dropna()

        max_win_streak = 0
        max_loss_streak = 0
        current_streak = 0
        streak_type = None  # "win" or "loss"

        for pnl in pnl_values:
            if pnl > 0:
                if streak_type == "win":
                    current_streak += 1
                else:
                    current_streak = 1
                    streak_type = "win"
                max_win_streak = max(max_win_streak, current_streak)
            else:
                if streak_type == "loss":
                    current_streak += 1
                else:
                    current_streak = 1
                    streak_type = "loss"
                max_loss_streak = max(max_loss_streak, current_streak)

        return {
            "max_win_streak": max_win_streak,
            "max_loss_streak": max_loss_streak,
            "current_streak": current_streak,
            "current_streak_type": streak_type or "none"
        }

    def generate_recommendations(self):
        """Generate actionable recommendations based on analysis."""
        recommendations = []

        # Symbol analysis
        symbol_stats = self.analyze_by_symbol()
        for symbol, stats in symbol_stats.items():
            if stats.get("recommendation", "").startswith("REMOVE"):
                recommendations.append({
                    "priority": "HIGH",
                    "type": "SYMBOL",
                    "action": f"Remove {symbol} from trading",
                    "reason": f"Win rate {stats['win_rate']}% with PnL ${stats['total_pnl']}",
                    "data": stats
                })
            elif stats.get("recommendation", "").startswith("REDUCE"):
                recommendations.append({
                    "priority": "MEDIUM",
                    "type": "SYMBOL",
                    "action": f"Reduce risk on {symbol}",
                    "reason": f"Win rate {stats['win_rate']}%, PF {stats['profit_factor']}",
                    "data": stats
                })

        # Session analysis
        session_stats = self.analyze_by_session()
        for session, stats in session_stats.items():
            if isinstance(stats, dict) and stats.get("trades", 0) >= 5:
                if stats.get("win_rate", 50) < 35:
                    recommendations.append({
                        "priority": "HIGH",
                        "type": "SESSION",
                        "action": f"Consider disabling {session} session",
                        "reason": f"Win rate {stats['win_rate']}%",
                        "data": stats
                    })

        # Streak analysis
        streaks = self.analyze_streaks()
        if streaks.get("max_loss_streak", 0) >= 5:
            recommendations.append({
                "priority": "HIGH",
                "type": "RISK",
                "action": "Reduce risk per trade to 0.25%",
                "reason": f"Max losing streak of {streaks['max_loss_streak']}",
                "data": streaks
            })

        # Day of week analysis
        day_stats = self.analyze_by_day_of_week()
        for day, stats in day_stats.items():
            if stats.get("trades", 0) >= 3 and stats.get("win_rate", 50) < 25:
                recommendations.append({
                    "priority": "MEDIUM",
                    "type": "SCHEDULE",
                    "action": f"Avoid trading on {day}",
                    "reason": f"Win rate {stats.get('win_rate', 0)}%",
                    "data": stats
                })

        return recommendations

    def generate_full_report(self):
        """Generate a comprehensive analysis report."""
        report = {
            "generated_at": datetime.now().isoformat(),
            "total_trades": len(self.trades),
            "symbol_analysis": self.analyze_by_symbol(),
            "session_analysis": self.analyze_by_session(),
            "day_analysis": self.analyze_by_day_of_week(),
            "streak_analysis": self.analyze_streaks(),
            "recommendations": self.generate_recommendations()
        }

        # Overall stats
        if not self.trades.empty and "PnL" in self.trades.columns:
            pnl = pd.to_numeric(self.trades["PnL"], errors="coerce").dropna()
            report["overall"] = {
                "total_pnl": round(float(pnl.sum()), 2),
                "win_rate": round(float((pnl > 0).sum() / len(pnl) * 100), 1) if len(pnl) > 0 else 0,
                "avg_pnl": round(float(pnl.mean()), 2) if len(pnl) > 0 else 0,
                "std_pnl": round(float(pnl.std()), 2) if len(pnl) > 1 else 0,
                "sharpe": round(
                    float(pnl.mean() / pnl.std()) * np.sqrt(252) if pnl.std() > 0 else 0, 2
                ),
                "max_drawdown_trade": round(float(pnl.min()), 2) if len(pnl) > 0 else 0,
                "best_trade": round(float(pnl.max()), 2) if len(pnl) > 0 else 0,
            }

        # Save report
        report_file = self.output_dir / f"analysis_{datetime.now().strftime('%Y%m%d_%H%M%S')}.json"
        with open(report_file, "w") as f:
            json.dump(report, f, indent=2, default=str)

        print(f"Report saved to {report_file}")
        return report

    def print_report(self, report=None):
        """Print a human-readable report."""
        if report is None:
            report = self.generate_full_report()

        print("\n" + "=" * 60)
        print("  PROPFIRMBOT - TRADE ANALYSIS REPORT")
        print("=" * 60)

        # Overall
        overall = report.get("overall", {})
        print(f"\nTotal Trades: {report.get('total_trades', 0)}")
        print(f"Total PnL: ${overall.get('total_pnl', 0)}")
        print(f"Win Rate: {overall.get('win_rate', 0)}%")
        print(f"Avg PnL/Trade: ${overall.get('avg_pnl', 0)}")
        print(f"Sharpe Ratio: {overall.get('sharpe', 0)}")

        # Symbol breakdown
        print("\n--- PER SYMBOL ---")
        for symbol, stats in report.get("symbol_analysis", {}).items():
            print(f"  {symbol}: {stats['trades']} trades | "
                  f"WR={stats['win_rate']}% | PF={stats['profit_factor']} | "
                  f"PnL=${stats['total_pnl']} | {stats.get('recommendation', '')}")

        # Session breakdown
        print("\n--- PER SESSION ---")
        for session, stats in report.get("session_analysis", {}).items():
            if isinstance(stats, dict) and "trades" in stats:
                print(f"  {session}: {stats['trades']} trades | "
                      f"WR={stats.get('win_rate', 'N/A')}% | PnL=${stats['total_pnl']}")

        # Recommendations
        recs = report.get("recommendations", [])
        if recs:
            print("\n--- RECOMMENDATIONS ---")
            for rec in sorted(recs, key=lambda x: {"HIGH": 0, "MEDIUM": 1, "LOW": 2}.get(x["priority"], 3)):
                print(f"  [{rec['priority']}] {rec['action']} - {rec['reason']}")
        else:
            print("\n  No recommendations - performance is acceptable.")

        print("\n" + "=" * 60)


def main():
    """Main entry point for standalone analysis."""
    analyzer = TradeAnalyzer()

    # Try to load journal data
    if analyzer.load_journal(days_back=30):
        report = analyzer.generate_full_report()
        analyzer.print_report(report)
    else:
        print("No trade data available for analysis.")
        print("The analyzer will work once the bot starts trading and generating journal files.")
        print(f"Expected journal location: {analyzer.journal_dir}")


if __name__ == "__main__":
    main()
