#!/bin/bash
# Weekly review — reads logs/trades_log.csv and prints aggregates
# (win-rate per strategy / per symbol / per hour-of-day).
#
# Usage (local):     bash scripts/weekly_review.sh
# Usage (VPS via commands/run.sh): cat report generated by this script.

set -u
cd "$(dirname "$0")/.."

TRADES_LOG="${1:-logs/trades_log.csv}"

if [ ! -f "$TRADES_LOG" ]; then
    echo "No trades log found at: $TRADES_LOG"
    exit 0
fi

python3 - "$TRADES_LOG" <<'PY'
import csv
import sys
from collections import Counter, defaultdict
from datetime import datetime

path = sys.argv[1]
rows = []
try:
    with open(path) as f:
        reader = csv.DictReader(f)
        for r in reader:
            rows.append(r)
except Exception as e:
    print(f"Failed to read {path}: {e}")
    sys.exit(0)

if not rows:
    print("No trades recorded yet.")
    sys.exit(0)

def to_float(x, default=0.0):
    try:
        return float(x)
    except (TypeError, ValueError):
        return default

total = len(rows)
wins = sum(1 for r in rows if to_float(r.get("pnl")) > 0)
losses = total - wins
total_pnl = sum(to_float(r.get("pnl")) for r in rows)
best = max(rows, key=lambda r: to_float(r.get("pnl")), default=None)
worst = min(rows, key=lambda r: to_float(r.get("pnl")), default=None)

print("=" * 60)
print("WEEKLY TRADE REVIEW")
print("=" * 60)
print(f"Total trades : {total}")
print(f"Wins / Losses: {wins} / {losses}")
print(f"Win rate     : {wins/total*100:.1f}%")
print(f"Total PnL    : ${total_pnl:+.2f}")
if best:
    print(f"Best trade   : ${to_float(best.get('pnl')):+.2f} on {best.get('symbol','?')}")
if worst:
    print(f"Worst trade  : ${to_float(worst.get('pnl')):+.2f} on {worst.get('symbol','?')}")

# Breakdown by strategy
print("\nBy strategy:")
by_strat = defaultdict(lambda: [0, 0, 0.0])  # [trades, wins, pnl]
for r in rows:
    s = r.get("strategy", "") or "unknown"
    pnl = to_float(r.get("pnl"))
    by_strat[s][0] += 1
    if pnl > 0:
        by_strat[s][1] += 1
    by_strat[s][2] += pnl
for s, (t, w, p) in sorted(by_strat.items()):
    wr = (w / t * 100) if t else 0
    print(f"  {s:<24} trades={t:<4} WR={wr:5.1f}%  PnL=${p:+.2f}")

# Breakdown by symbol
print("\nBy symbol:")
by_sym = defaultdict(lambda: [0, 0, 0.0])
for r in rows:
    s = r.get("symbol", "") or "?"
    pnl = to_float(r.get("pnl"))
    by_sym[s][0] += 1
    if pnl > 0:
        by_sym[s][1] += 1
    by_sym[s][2] += pnl
for s, (t, w, p) in sorted(by_sym.items()):
    wr = (w / t * 100) if t else 0
    print(f"  {s:<24} trades={t:<4} WR={wr:5.1f}%  PnL=${p:+.2f}")

# Breakdown by hour (UTC — converted roughly to ET by -4h/EDT)
print("\nBy hour (approx. ET):")
by_hour = defaultdict(lambda: [0, 0, 0.0])
for r in rows:
    ts = r.get("timestamp_utc", "")
    try:
        dt = datetime.fromisoformat(ts.replace("Z", "+00:00"))
        hour_et = (dt.hour - 4) % 24  # rough EDT
    except Exception:
        continue
    pnl = to_float(r.get("pnl"))
    by_hour[hour_et][0] += 1
    if pnl > 0:
        by_hour[hour_et][1] += 1
    by_hour[hour_et][2] += pnl
for h in sorted(by_hour.keys()):
    t, w, p = by_hour[h]
    wr = (w / t * 100) if t else 0
    print(f"  {h:02d}:00 ET  trades={t:<4} WR={wr:5.1f}%  PnL=${p:+.2f}")

# Longest loss streak
streak = 0
max_streak = 0
for r in rows:
    if to_float(r.get("pnl")) < 0:
        streak += 1
        max_streak = max(max_streak, streak)
    else:
        streak = 0
print(f"\nLongest loss streak: {max_streak}")

print("=" * 60)
PY
